import { Product, Category, Sale } from '@/types';

export const sampleCategories: Category[] = [
  {
    id: '1',
    name: 'الإلكترونيات',
    description: 'الأجهزة الإلكترونية والتقنية',
    subcategories: [
      {
        id: '1-1',
        name: 'الهواتف الذكية',
        description: 'هواتف ذكية وإكسسوارات',
        categoryId: '1',
      },
      {
        id: '1-2',
        name: 'أجهزة الكمبيوتر',
        description: 'أجهزة كمبيوتر ولابتوب',
        categoryId: '1',
      },
    ],
  },
  {
    id: '2',
    name: 'الملابس',
    description: 'الملابس والأزياء',
    subcategories: [
      {
        id: '2-1',
        name: 'ملابس رجالية',
        description: 'ملابس للرجال',
        categoryId: '2',
      },
      {
        id: '2-2',
        name: 'ملابس نسائية',
        description: 'ملابس للنساء',
        categoryId: '2',
      },
    ],
  },
  {
    id: '3',
    name: 'المنزل والحديقة',
    description: 'أدوات منزلية ومستلزمات الحديقة',
    subcategories: [
      {
        id: '3-1',
        name: 'أدوات المطبخ',
        description: 'أدوات ومعدات المطبخ',
        categoryId: '3',
      },
      {
        id: '3-2',
        name: 'أثاث المنزل',
        description: 'أثاث وديكورات منزلية',
        categoryId: '3',
      },
    ],
  },
  {
    id: '4',
    name: 'المواد الغذائية',
    description: 'مواد غذائية وبقالة',
    subcategories: [],
  },
];

export const sampleProducts: Product[] = [
  {
    id: '1',
    name: 'iPhone 15 Pro',
    description: 'هاتف ذكي من آبل بأحدث التقنيات',
    category: 'الإلكترونيات',
    subcategory: 'الهواتف الذكية',
    wholesalePrice: 1400000,
    salePrice: 1680000,
    discount: 5,
    measurementType: 'quantity',
    quantity: 25,
    minQuantity: 5,
    barcode: '1234567890123',
    currency: 'IQD',
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '2',
    name: 'Samsung Galaxy S24',
    description: 'هاتف ذكي من سامسونج بكاميرا عالية الجودة',
    category: 'الإلكترونيات',
    subcategory: 'الهواتف الذكية',
    wholesalePrice: 1200000,
    salePrice: 1440000,
    discount: 0,
    measurementType: 'quantity',
    quantity: 15,
    minQuantity: 5,
    barcode: '1234567890124',
    currency: 'IQD',
    createdAt: new Date('2024-01-20'),
    updatedAt: new Date('2024-01-20'),
  },
  {
    id: '3',
    name: 'MacBook Air M3',
    description: 'لابتوب من آبل بمعالج M3',
    category: 'الإلكترونيات',
    subcategory: 'أجهزة الكمبيوتر',
    wholesalePrice: 1100,
    salePrice: 1320,
    discount: 3,
    measurementType: 'quantity',
    quantity: 8,
    minQuantity: 3,
    barcode: '1234567890125',
    currency: 'USD',
    createdAt: new Date('2024-01-25'),
    updatedAt: new Date('2024-01-25'),
  },
  {
    id: '4',
    name: 'قميص قطني رجالي',
    description: 'قميص قطني عالي الجودة للرجال',
    category: 'الملابس',
    subcategory: 'ملابس رجالية',
    wholesalePrice: 32000,
    salePrice: 48000,
    discount: 10,
    measurementType: 'quantity',
    quantity: 50,
    minQuantity: 10,
    barcode: '1234567890126',
    currency: 'IQD',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '5',
    name: 'فستان صيفي نسائي',
    description: 'فستان صيفي أنيق للنساء',
    category: 'الملابس',
    subcategory: 'ملابس نسائية',
    wholesalePrice: 35,
    salePrice: 52,
    discount: 15,
    measurementType: 'quantity',
    quantity: 30,
    minQuantity: 8,
    barcode: '1234567890127',
    currency: 'USD',
    createdAt: new Date('2024-02-05'),
    updatedAt: new Date('2024-02-05'),
  },
  {
    id: '6',
    name: 'طقم أواني طبخ',
    description: 'طقم أواني طبخ من الستانلس ستيل',
    category: 'المنزل والحديقة',
    subcategory: 'أدوات المطبخ',
    wholesalePrice: 120000,
    salePrice: 180000,
    discount: 5,
    measurementType: 'quantity',
    quantity: 12,
    minQuantity: 5,
    barcode: '1234567890128',
    currency: 'IQD',
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  },
  {
    id: '7',
    name: 'كرسي مكتب مريح',
    description: 'كرسي مكتب بتصميم مريح وعملي',
    category: 'المنزل والحديقة',
    subcategory: 'أثاث المنزل',
    wholesalePrice: 180,
    salePrice: 270,
    discount: 8,
    measurementType: 'quantity',
    quantity: 6,
    minQuantity: 3,
    barcode: '1234567890129',
    currency: 'USD',
    createdAt: new Date('2024-02-15'),
    updatedAt: new Date('2024-02-15'),
  },
  {
    id: '8',
    name: 'سماعات لاسلكية',
    description: 'سماعات بلوتوث عالية الجودة',
    category: 'الإلكترونيات',
    subcategory: 'الهواتف الذكية',
    wholesalePrice: 80000,
    salePrice: 120000,
    discount: 0,
    measurementType: 'quantity',
    quantity: 2,
    minQuantity: 5,
    barcode: '1234567890130',
    currency: 'IQD',
    createdAt: new Date('2024-02-20'),
    updatedAt: new Date('2024-02-20'),
  },
  {
    id: '9',
    name: 'جاكيت شتوي رجالي',
    description: 'جاكيت شتوي دافئ للرجال',
    category: 'الملابس',
    subcategory: 'ملابس رجالية',
    wholesalePrice: 60,
    salePrice: 90,
    discount: 12,
    measurementType: 'quantity',
    quantity: 0,
    minQuantity: 5,
    barcode: '1234567890131',
    currency: 'USD',
    createdAt: new Date('2024-02-25'),
    updatedAt: new Date('2024-02-25'),
  },
  {
    id: '10',
    name: 'طاولة قهوة خشبية',
    description: 'طاولة قهوة من الخشب الطبيعي',
    category: 'المنزل والحديقة',
    subcategory: 'أثاث المنزل',
    wholesalePrice: 240000,
    salePrice: 360000,
    discount: 0,
    measurementType: 'quantity',
    quantity: 4,
    minQuantity: 2,
    barcode: '1234567890132',
    currency: 'IQD',
    createdAt: new Date('2024-03-01'),
    updatedAt: new Date('2024-03-01'),
  },
  // Weight-based products
  {
    id: '11',
    name: 'أرز بسمتي',
    description: 'أرز بسمتي فاخر من الهند',
    category: 'المواد الغذائية',
    wholesalePrice: 8000,
    salePrice: 12000,
    discount: 0,
    measurementType: 'weight',
    weightUnit: 'kg',
    weight: 150.5,
    minWeight: 20,
    quantity: 0,
    minQuantity: 0,
    barcode: '1234567890133',
    currency: 'IQD',
    createdAt: new Date('2024-03-05'),
    updatedAt: new Date('2024-03-05'),
  },
  {
    id: '12',
    name: 'سكر أبيض',
    description: 'سكر أبيض نقي',
    category: 'المواد الغذائية',
    wholesalePrice: 5000,
    salePrice: 7500,
    discount: 5,
    measurementType: 'weight',
    weightUnit: 'kg',
    weight: 85.3,
    minWeight: 25,
    quantity: 0,
    minQuantity: 0,
    barcode: '1234567890134',
    currency: 'IQD',
    createdAt: new Date('2024-03-06'),
    updatedAt: new Date('2024-03-06'),
  },
  {
    id: '13',
    name: 'لحم بقري طازج',
    description: 'لحم بقري طازج عالي الجودة',
    category: 'المواد الغذائية',
    wholesalePrice: 32000,
    salePrice: 45000,
    discount: 0,
    measurementType: 'weight',
    weightUnit: 'kg',
    weight: 12.7,
    minWeight: 5,
    quantity: 0,
    minQuantity: 0,
    barcode: '1234567890135',
    currency: 'IQD',
    createdAt: new Date('2024-03-07'),
    updatedAt: new Date('2024-03-07'),
  },
  {
    id: '14',
    name: 'زعفران فاخر',
    description: 'زعفران إيراني أصلي',
    category: 'المواد الغذائية',
    wholesalePrice: 150000,
    salePrice: 225000,
    discount: 0,
    measurementType: 'weight',
    weightUnit: 'g',
    weight: 250.5,
    minWeight: 50,
    quantity: 0,
    minQuantity: 0,
    barcode: '1234567890136',
    currency: 'IQD',
    createdAt: new Date('2024-03-08'),
    updatedAt: new Date('2024-03-08'),
  },
  {
    id: '15',
    name: 'قهوة عربية',
    description: 'قهوة عربية محمصة طازجة',
    category: 'المواد الغذائية',
    wholesalePrice: 24000,
    salePrice: 36000,
    discount: 10,
    measurementType: 'weight',
    weightUnit: 'kg',
    weight: 3.2,
    minWeight: 5,
    quantity: 0,
    minQuantity: 0,
    barcode: '1234567890137',
    currency: 'IQD',
    createdAt: new Date('2024-03-09'),
    updatedAt: new Date('2024-03-09'),
  },
];

export const sampleSales: Sale[] = [
  {
    id: '1',
    productId: '1',
    product: sampleProducts[0],
    quantity: 2,
    unitPrice: 3990, // سعر البيع بعد الخصم
    totalPrice: 7980,
    discount: 5,
    finalPrice: 7980,
    customerName: 'أحمد محمد',
    customerPhone: '0501234567',
    paymentMethod: 'card',
    saleDate: new Date('2024-03-15T10:30:00'),
  },
  {
    id: '2',
    productId: '4',
    product: sampleProducts[3],
    quantity: 3,
    unitPrice: 108, // سعر البيع بعد الخصم
    totalPrice: 324,
    discount: 10,
    finalPrice: 324,
    customerName: 'فاطمة علي',
    customerPhone: '0507654321',
    paymentMethod: 'cash',
    saleDate: new Date('2024-03-16T14:15:00'),
  },
  {
    id: '3',
    productId: '5',
    product: sampleProducts[4],
    quantity: 1,
    unitPrice: 187, // سعر البيع بعد الخصم
    totalPrice: 187,
    discount: 15,
    finalPrice: 187,
    customerName: 'مريم خالد',
    paymentMethod: 'transfer',
    saleDate: new Date('2024-03-17T16:45:00'),
  },
  {
    id: '4',
    productId: '2',
    product: sampleProducts[1],
    quantity: 1,
    unitPrice: 3600,
    totalPrice: 3600,
    discount: 0,
    finalPrice: 3600,
    customerName: 'سعد الأحمد',
    customerPhone: '0509876543',
    paymentMethod: 'card',
    saleDate: new Date('2024-03-18T11:20:00'),
  },
  {
    id: '5',
    productId: '6',
    product: sampleProducts[5],
    quantity: 2,
    unitPrice: 427.5, // سعر البيع بعد الخصم
    totalPrice: 855,
    discount: 5,
    finalPrice: 855,
    customerName: 'نورا سالم',
    paymentMethod: 'cash',
    saleDate: new Date('2024-03-19T09:10:00'),
  },
  {
    id: '6',
    productId: '3',
    product: sampleProducts[2],
    quantity: 1,
    unitPrice: 5238, // سعر البيع بعد الخصم
    totalPrice: 5238,
    discount: 3,
    finalPrice: 5238,
    customerName: 'عبدالله يوسف',
    customerPhone: '0502468135',
    paymentMethod: 'transfer',
    saleDate: new Date('2024-03-20T13:30:00'),
  },
  {
    id: '7',
    productId: '8',
    product: sampleProducts[7],
    quantity: 3,
    unitPrice: 300,
    totalPrice: 900,
    discount: 0,
    finalPrice: 900,
    customerName: 'ليلى حسن',
    paymentMethod: 'card',
    saleDate: new Date('2024-03-21T15:45:00'),
  },
  {
    id: '8',
    productId: '4',
    product: sampleProducts[3],
    quantity: 5,
    unitPrice: 108,
    totalPrice: 540,
    discount: 10,
    finalPrice: 540,
    customerName: 'محمد العتيبي',
    customerPhone: '0501357924',
    paymentMethod: 'cash',
    saleDate: new Date('2024-03-22T12:15:00'),
  },
];

export function initializeSampleData() {
  // Check if data already exists
  const existingProducts = localStorage.getItem('warehouse_products');
  const existingCategories = localStorage.getItem('warehouse_categories');
  const existingSales = localStorage.getItem('warehouse_sales');

  if (!existingCategories) {
    localStorage.setItem('warehouse_categories', JSON.stringify(sampleCategories));
  }

  if (!existingProducts) {
    localStorage.setItem('warehouse_products', JSON.stringify(sampleProducts));
  }

  if (!existingSales) {
    localStorage.setItem('warehouse_sales', JSON.stringify(sampleSales));
  }
}
